export type VendorStatus = "Active" | "Inactive" | "Active";

export type VendorDirectoryRow = {
  vendorName: string;
  vendorCode: string;
  category: string;
  contactPerson: string;
  city: string;
  rating: number;
  status: VendorStatus;
  lastTransaction: string;
  totalPurchaseValue: number;
};

export const vendorDirectoryMockData: VendorDirectoryRow[] = [
  {
    vendorName: "Atlas Industrial Supplies",
    vendorCode: "VND-1001",
    category: "Raw Materials",
    contactPerson: "Maya Sharma",
    city: "Mumbai",
    rating: 4.7,
    status: "Active",
    lastTransaction: "2026-07-21",
    totalPurchaseValue: 1284500,
  },
  {
    vendorName: "BluePeak Electronics",
    vendorCode: "VND-1002",
    category: "Electronics",
    contactPerson: "Arjun Rao",
    city: "Bengaluru",
    rating: 4.4,
    status: "Active",
    lastTransaction: "2026-07-19",
    totalPurchaseValue: 972300,
  },
  {
    vendorName: "Crestline Packaging Co.",
    vendorCode: "VND-1003",
    category: "Packaging",
    contactPerson: "Nisha Verma",
    city: "Pune",
    rating: 4.2,
    status: "Active",
    lastTransaction: "2026-06-30",
    totalPurchaseValue: 645900,
  },
  {
    vendorName: "Delta Office Works",
    vendorCode: "VND-1004",
    category: "Office Supplies",
    contactPerson: "Rohan Kapoor",
    city: "Delhi",
    rating: 3.9,
    status: "Active",
    lastTransaction: "2026-07-16",
    totalPurchaseValue: 318750,
  },
  {
    vendorName: "EcoPure Chemicals",
    vendorCode: "VND-1005",
    category: "Chemicals",
    contactPerson: "Priya Nair",
    city: "Hyderabad",
    rating: 4.6,
    status: "Active",
    lastTransaction: "2026-07-20",
    totalPurchaseValue: 1542200,
  },
  {
    vendorName: "Fusion Freight Services",
    vendorCode: "VND-1006",
    category: "Logistics",
    contactPerson: "Karan Mehta",
    city: "Ahmedabad",
    rating: 4.1,
    status: "Inactive",
    lastTransaction: "2026-05-11",
    totalPurchaseValue: 487600,
  },
  {
    vendorName: "GreenGrid Energy Systems",
    vendorCode: "VND-1007",
    category: "Utilities",
    contactPerson: "Simran Gill",
    city: "Chandigarh",
    rating: 4.8,
    status: "Active",
    lastTransaction: "2026-07-23",
    totalPurchaseValue: 2113900,
  },
  {
    vendorName: "Horizon Textiles",
    vendorCode: "VND-1008",
    category: "Textiles",
    contactPerson: "Ishaan Malhotra",
    city: "Surat",
    rating: 4.0,
    status: "Active",
    lastTransaction: "2026-06-18",
    totalPurchaseValue: 733200,
  },
  {
    vendorName: "IonTech Components",
    vendorCode: "VND-1009",
    category: "Spare Parts",
    contactPerson: "Ananya Iyer",
    city: "Chennai",
    rating: 4.5,
    status: "Active",
    lastTransaction: "2026-07-22",
    totalPurchaseValue: 1268400,
  },
  {
    vendorName: "Jupiter Safety Gear",
    vendorCode: "VND-1010",
    category: "Safety Equipment",
    contactPerson: "Vikram Desai",
    city: "Nagpur",
    rating: 3.8,
    status: "Inactive",
    lastTransaction: "2026-04-27",
    totalPurchaseValue: 269500,
  },
  {
    vendorName: "Kinetic Machine Tools",
    vendorCode: "VND-1011",
    category: "Machinery",
    contactPerson: "Neha Bhatia",
    city: "Coimbatore",
    rating: 4.3,
    status: "Active",
    lastTransaction: "2026-07-15",
    totalPurchaseValue: 1827600,
  },
  {
    vendorName: "Lumen Lighting Pvt Ltd",
    vendorCode: "VND-1012",
    category: "Electrical",
    contactPerson: "Aditya Sen",
    city: "Kolkata",
    rating: 4.1,
    status: "Active",
    lastTransaction: "2026-07-14",
    totalPurchaseValue: 589300,
  },
  {
    vendorName: "Metro Alloy Traders",
    vendorCode: "VND-1013",
    category: "Metals",
    contactPerson: "Rahul Sinha",
    city: "Jaipur",
    rating: 4.2,
    status: "Active",
    lastTransaction: "2026-07-18",
    totalPurchaseValue: 914200,
  },
  {
    vendorName: "Nova Cleanroom Solutions",
    vendorCode: "VND-1014",
    category: "Facility Services",
    contactPerson: "Sneha Kulkarni",
    city: "Nashik",
    rating: 4.0,
    status: "Active",
    lastTransaction: "2026-06-26",
    totalPurchaseValue: 402800,
  },
  {
    vendorName: "Orbit Agro Inputs",
    vendorCode: "VND-1015",
    category: "Agricultural Supplies",
    contactPerson: "Harsh Patel",
    city: "Indore",
    rating: 3.9,
    status: "Active",
    lastTransaction: "2026-07-11",
    totalPurchaseValue: 557900,
  },
  {
    vendorName: "PrimeFlex Polymers",
    vendorCode: "VND-1016",
    category: "Polymers",
    contactPerson: "Meera Joshi",
    city: "Vadodara",
    rating: 4.3,
    status: "Active",
    lastTransaction: "2026-07-20",
    totalPurchaseValue: 1196700,
  },
  {
    vendorName: "Quantum IT Peripherals",
    vendorCode: "VND-1017",
    category: "IT Hardware",
    contactPerson: "Farhan Ali",
    city: "Noida",
    rating: 4.5,
    status: "Active",
    lastTransaction: "2026-07-23",
    totalPurchaseValue: 1362400,
  },
  {
    vendorName: "RapidPrint Labels",
    vendorCode: "VND-1018",
    category: "Printing",
    contactPerson: "Divya Arora",
    city: "Ludhiana",
    rating: 3.7,
    status: "Inactive",
    lastTransaction: "2026-03-29",
    totalPurchaseValue: 198300,
  },
  {
    vendorName: "Sterling Fasteners",
    vendorCode: "VND-1019",
    category: "Hardware",
    contactPerson: "Yash Chawla",
    city: "Faridabad",
    rating: 4.4,
    status: "Active",
    lastTransaction: "2026-07-09",
    totalPurchaseValue: 821500,
  },
  {
    vendorName: "TerraBuild Cement Works",
    vendorCode: "VND-1020",
    category: "Construction",
    contactPerson: "Nitin Arvind",
    city: "Bhopal",
    rating: 4.1,
    status: "Active",
    lastTransaction: "2026-06-21",
    totalPurchaseValue: 1013800,
  },
  {
    vendorName: "Urban Cold Chain",
    vendorCode: "VND-1021",
    category: "Logistics",
    contactPerson: "Pooja Khanna",
    city: "Lucknow",
    rating: 4.0,
    status: "Active",
    lastTransaction: "2026-07-17",
    totalPurchaseValue: 690400,
  },
  {
    vendorName: "Vertex Automation",
    vendorCode: "VND-1022",
    category: "Automation",
    contactPerson: "Aman Oberoi",
    city: "Gurugram",
    rating: 4.6,
    status: "Active",
    lastTransaction: "2026-07-22",
    totalPurchaseValue: 1749200,
  },
  {
    vendorName: "Waveform Instruments",
    vendorCode: "VND-1023",
    category: "Testing Equipment",
    contactPerson: "Tanvi Prasad",
    city: "Mysuru",
    rating: 4.2,
    status: "Active",
    lastTransaction: "2026-07-13",
    totalPurchaseValue: 763100,
  },
  {
    vendorName: "Xylon Timber Merchants",
    vendorCode: "VND-1024",
    category: "Wood",
    contactPerson: "Saket Roy",
    city: "Raipur",
    rating: 3.8,
    status: "Inactive",
    lastTransaction: "2026-04-19",
    totalPurchaseValue: 286700,
  },
  {
    vendorName: "YieldPro Seeds",
    vendorCode: "VND-1025",
    category: "Agricultural Supplies",
    contactPerson: "Komal Reddy",
    city: "Vijayawada",
    rating: 4.3,
    status: "Active",
    lastTransaction: "2026-07-12",
    totalPurchaseValue: 534900,
  },
  {
    vendorName: "Zenith Medical Consumables",
    vendorCode: "VND-1026",
    category: "Healthcare",
    contactPerson: "Ritika Paul",
    city: "Kochi",
    rating: 4.7,
    status: "Active",
    lastTransaction: "2026-07-24",
    totalPurchaseValue: 1438600,
  },
  {
    vendorName: "AeroFab Components",
    vendorCode: "VND-1027",
    category: "Aerospace Parts",
    contactPerson: "Manav Gupta",
    city: "Pune",
    rating: 4.5,
    status: "Active",
    lastTransaction: "2026-06-15",
    totalPurchaseValue: 1673000,
  },
  {
    vendorName: "BrightLine Signage",
    vendorCode: "VND-1028",
    category: "Branding",
    contactPerson: "Shalini Bose",
    city: "Kolkata",
    rating: 3.9,
    status: "Active",
    lastTransaction: "2026-07-10",
    totalPurchaseValue: 348600,
  },
  {
    vendorName: "CoreHeat Furnaces",
    vendorCode: "VND-1029",
    category: "Industrial Equipment",
    contactPerson: "Pranav Menon",
    city: "Chennai",
    rating: 4.4,
    status: "Active",
    lastTransaction: "2026-07-08",
    totalPurchaseValue: 1299500,
  },
  {
    vendorName: "DynaLab Reagents",
    vendorCode: "VND-1030",
    category: "Laboratory",
    contactPerson: "Ira Banerjee",
    city: "Hyderabad",
    rating: 4.2,
    status: "Inactive",
    lastTransaction: "2026-05-06",
    totalPurchaseValue: 472100,
  },
  {
    vendorName: "EverSpan Pipes",
    vendorCode: "VND-1031",
    category: "Plumbing",
    contactPerson: "Deepak Solanki",
    city: "Kanpur",
    rating: 4.1,
    status: "Active",
    lastTransaction: "2026-07-05",
    totalPurchaseValue: 624400,
  },
  {
    vendorName: "FlexiCart Distribution",
    vendorCode: "VND-1032",
    category: "Distribution",
    contactPerson: "Nandini Shekhar",
    city: "Patna",
    rating: 4.0,
    status: "Active",
    lastTransaction: "2026-06-11",
    totalPurchaseValue: 539800,
  },
];
